version: '3.5'

services:
  apache:
    container_name: apache
    image: apache
    build:
      context: .docker
      dockerfile: .docker/app/Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - '8000:80'
