version: '3.5'

services:
  apache:
    container_name: apache
    image: apache
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ..:/var/www/html/
    ports:
      - '8000:80'
